project_id = "karcxgnfiymlrkbzhewo"

[auth]
enabled = true
external_url = "https://karcxgnfiymlrkbzhewo.supabase.co"
schema = "auth"
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]

[db]
password = "postgres"
shadow_database_url = "postgresql://postgres:postgres@127.0.0.1:54320/postgres"

[functions.prospeccao-status]
verify_jwt = false

[functions.prospeccao-anotacao]
verify_jwt = false

[functions.trigger-webhook] 
verify_jwt = true

[functions.manage-users]
verify_jwt = true

[functions.opt-out-check]
verify_jwt = true

[functions.maia-webhook-proxy]
verify_jwt = true

[functions.atendimento-status-webhook]
verify_jwt = true

[functions.ia-ligacao-webhook]
verify_jwt = true

[functions.sync-empresas]
verify_jwt = false

[functions.validate-domain]
verify_jwt = false

[functions.cleanup-invalid-users]
verify_jwt = false

[functions.dispatch-leads-webhook]
verify_jwt = true

[functions.eventos-ligacao-proxy]
verify_jwt = true

[functions.sync-eventos-ligacao]
verify_jwt = true

[functions.sync-contatos-ligacao]
verify_jwt = true

[functions.get-lead-qrcode]
verify_jwt = false

[functions.external-webhook-proxy]
verify_jwt = true

[functions.create-base-ligacao]
verify_jwt = true

[functions.get-base-ligacao]
verify_jwt = true

[functions.sync-pri-dashboard]
verify_jwt = true

[functions.academy-voice-simulation]
verify_jwt = false

[functions.academy-generate-training]
verify_jwt = false

[functions.academy-voice-preview]
verify_jwt = false

[functions.academy-generate-simulation]
verify_jwt = false

[functions.create-lead]
verify_jwt = false

[functions.search-lead]
verify_jwt = false

[functions.cotacao-dolar]
verify_jwt = true

[functions.notify-evento-criado]
verify_jwt = false

[functions.send-crm-event-email]
verify_jwt = false

[functions.process-campaign-job]
verify_jwt = false

[functions.resync-lead-ids]
verify_jwt = true

[functions.fetch-call-costs]
verify_jwt = false

[functions.process-import]
verify_jwt = false

[functions.create-lead-ligacao]
verify_jwt = false

[functions.template-paused-webhook]
verify_jwt = false

[functions.reset-disparos-pendente]
verify_jwt = false

[functions.fetch-vapi-metrics]
verify_jwt = true

[functions.fetch-twilio-metrics]
verify_jwt = true

[functions.ingest-base-clientes]
verify_jwt = false

[functions.external-optout-register]
verify_jwt = true
