import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { supabase } from "@/integrations/supabase/client";
import { useQuery } from "@tanstack/react-query";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";
import { format } from "date-fns";

const optOutSchema = z.object({
  data_optout: z.string().min(1, "Data é obrigatória"),
  nome: z.string().min(1, "Nome é obrigatório"),
  telefone: z.string().optional(),
  email: z.string().email("E-mail inválido").optional().or(z.literal("")),
  canal: z.enum(["Whatsapp", "Ligação", "SMS", "E-mail"], {
    required_error: "Canal é obrigatório",
  }),
  empresa_id: z.string().min(1, "Empresa é obrigatória"),
});

type OptOutFormData = z.infer<typeof optOutSchema>;

interface OptOutModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSuccess: () => void;
  optOut?: any;
}

export function OptOutModal({ isOpen, onClose, onSuccess, optOut }: OptOutModalProps) {
  const { toast } = useToast();
  const [isSubmitting, setIsSubmitting] = useState(false);

  const { data: empresas } = useQuery({
    queryKey: ["empresas"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("empresas")
        .select("id, nome_empresa")
        .order("nome_empresa");
      if (error) throw error;
      return data;
    },
  });

  const {
    register,
    handleSubmit,
    setValue,
    watch,
    reset,
    formState: { errors },
  } = useForm<OptOutFormData>({
    resolver: zodResolver(optOutSchema),
    defaultValues: {
      data_optout: optOut 
        ? format(new Date(optOut.data_optout), "yyyy-MM-dd'T'HH:mm")
        : format(new Date(), "yyyy-MM-dd'T'HH:mm"),
      nome: optOut?.nome || "",
      telefone: optOut?.telefone_e164 || "",
      email: optOut?.email_normalizado || "",
      canal: optOut?.canal || "Whatsapp",
      empresa_id: optOut?.empresa_id || "00000000-0000-0000-0000-000000000001", // Default company
    },
  });

  const handleClose = () => {
    reset();
    onClose();
  };

  const onSubmit = async (data: OptOutFormData) => {
    setIsSubmitting(true);
    
    try {
      const insertData = {
        data_optout: new Date(data.data_optout).toISOString(),
        nome: data.nome || null,
        telefone_e164: data.telefone || null,
        email_normalizado: data.email || null,
        canal: data.canal,
        empresa_id: data.empresa_id || "00000000-0000-0000-0000-000000000001", // Always default to Empresa Padrão
        source: "UI",
        dedupe_key: "", // Will be generated by trigger
      };

      if (optOut) {
        const { error } = await supabase
          .from("opt_outs")
          .update(insertData)
          .eq("id", optOut.id);
        
        if (error) throw error;
        
        toast({
          title: "Opt-out atualizado",
          description: "Registro atualizado com sucesso",
        });
      } else {
        const { error } = await supabase
          .from("opt_outs")
          .insert([insertData]);
        
        if (error) throw error;
        
        toast({
          title: "Opt-out registrado",
          description: "Novo registro criado com sucesso",
        });
      }

      onSuccess();
    } catch (error: any) {
      console.error("Erro ao salvar opt-out:", error);
      
      if (error.code === "23505") {
        toast({
          title: "Opt-out já existe",
          description: "Já existe um opt-out para este canal e identificador. A data foi atualizada.",
        });
        onSuccess();
      } else {
        toast({
          title: "Erro ao salvar",
          description: error.message || "Erro inesperado",
          variant: "destructive",
        });
      }
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={handleClose}>
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle>
            {optOut ? "Editar" : "Novo"} Opt-out
          </DialogTitle>
        </DialogHeader>

        <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
          <div>
            <Label htmlFor="data_optout">Data do Opt-out *</Label>
            <Input
              id="data_optout"
              type="datetime-local"
              {...register("data_optout")}
              className={errors.data_optout ? "border-destructive" : ""}
            />
            {errors.data_optout && (
              <p className="text-sm text-destructive mt-1">
                {errors.data_optout.message}
              </p>
            )}
          </div>

          <div>
            <Label htmlFor="nome">Nome do Cliente *</Label>
            <Input
              id="nome"
              placeholder="Nome completo do cliente"
              {...register("nome")}
              className={errors.nome ? "border-destructive" : ""}
            />
            {errors.nome && (
              <p className="text-sm text-destructive mt-1">
                {errors.nome.message}
              </p>
            )}
          </div>

          <div>
            <Label htmlFor="telefone">Telefone</Label>
            <Input
              id="telefone"
              placeholder="+55 62 99999-9999"
              {...register("telefone")}
            />
          </div>

          <div>
            <Label htmlFor="email">E-mail</Label>
            <Input
              id="email"
              type="email"
              placeholder="cliente@exemplo.com"
              {...register("email")}
              className={errors.email ? "border-destructive" : ""}
            />
            {errors.email && (
              <p className="text-sm text-destructive mt-1">
                {errors.email.message}
              </p>
            )}
          </div>

          <div>
            <Label htmlFor="canal">Canal *</Label>
            <Select
              value={watch("canal")}
              onValueChange={(value) => setValue("canal", value as any)}
            >
              <SelectTrigger className={errors.canal ? "border-destructive" : ""}>
                <SelectValue placeholder="Selecione o canal" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="Whatsapp">WhatsApp</SelectItem>
                <SelectItem value="E-mail">E-mail</SelectItem>
                <SelectItem value="SMS">SMS</SelectItem>
                <SelectItem value="Ligação">Ligação</SelectItem>
              </SelectContent>
            </Select>
            {errors.canal && (
              <p className="text-sm text-destructive mt-1">
                {errors.canal.message}
              </p>
            )}
          </div>

          <div>
            <Label htmlFor="empresa_id">Empresa *</Label>
            <Select
              value={watch("empresa_id")}
              onValueChange={(value) => setValue("empresa_id", value)}
            >
              <SelectTrigger className={errors.empresa_id ? "border-destructive" : ""}>
                <SelectValue placeholder="Selecione a empresa" />
              </SelectTrigger>
              <SelectContent>
                {empresas?.map((empresa) => (
                  <SelectItem key={empresa.id} value={empresa.id}>
                    {empresa.nome_empresa}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            {errors.empresa_id && (
              <p className="text-sm text-destructive mt-1">
                {errors.empresa_id.message}
              </p>
            )}
          </div>

          <div className="flex gap-3 pt-4">
            <Button
              type="button"
              variant="outline"
              onClick={handleClose}
              className="flex-1"
              disabled={isSubmitting}
            >
              Cancelar
            </Button>
            <Button
              type="submit"
              className="flex-1"
              disabled={isSubmitting}
            >
              {isSubmitting ? "Salvando..." : optOut ? "Atualizar" : "Criar"}
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
}