-- Seed departamento_permissoes with current PermissionRegistry defaults
-- This ensures overrides work correctly when hardcoded logic is removed
-- DO NOTHING preserves any manually configured overrides

INSERT INTO departamento_permissoes (departamento, permissao, ativo)
VALUES
  ('SDR', 'canViewAuthenticator', false),
  ('SDR', 'canManageAuthenticator', false),
  ('SDR', 'canAssignAuthenticator', false),
  ('SDR', 'canViewAuditLogs', false),
  ('SDR', 'canViewControleAgentes', false),
  ('SDR', 'canCreateControleAgentes', false),
  ('SDR', 'canEditControleAgentes', false),
  ('SDR', 'canDeleteControleAgentes', false),
  ('SDR', 'canToggleControleAgentes', false),
  ('SDR', 'canAccessAgentesIA', false),
  ('SDR', 'canEditAgentesIA', false),
  ('SDR', 'canDeleteAgentesIA', false),
  ('SDR', 'canCreateAgentesIA', false),
  ('SDR', 'canManageInstancias', false),
  ('SDR', 'canViewVariaveis', false),
  ('SDR', 'canEditVariaveis', false),
  ('SDR', 'canManageCadencias', false),
  ('SDR', 'canManageFollowups', false),
  ('SDR', 'canManageIntegracoes', false),
  ('SDR', 'canViewTemplates', true),
  ('SDR', 'canCreateTemplates', false),
  ('SDR', 'canEditTemplates', false),
  ('SDR', 'canDeleteTemplates', false),
  ('SDR', 'canViewEventos', true),
  ('SDR', 'canCreateEventos', false),
  ('SDR', 'canEditEventos', false),
  ('SDR', 'canDeleteEventos', false),
  ('SDR', 'canManageEvents', true),
  ('SDR', 'canManageEventos', false),
  ('SDR', 'canCreateIALigacao', false),
  ('SDR', 'canDispararIALigacao', false),
  ('SDR', 'canToggleIALigacao', false),
  ('SDR', 'canViewIALigacaoLogs', false),
  ('SDR', 'canDispararEventos', false),
  ('SDR', 'canRedispararEventos', false),
  ('SDR', 'canAprovarCampanhas', false),
  ('SDR', 'canProgramarCampanhas', false),
  ('SDR', 'canViewClientes', true),
  ('SDR', 'canAddClientes', false),
  ('SDR', 'canEditClientes', false),
  ('SDR', 'canDeleteClientes', false),
  ('SDR', 'canImportClientes', false),
  ('SDR', 'canUploadBase', false),
  ('SDR', 'canEditContatos', true),
  ('SDR', 'canDeleteContatos', false),
  ('SDR', 'canValidarImportacao', false),
  ('SDR', 'canGovernancaDados', false),
  ('SDR', 'canAccessOptOutGlobal', false),
  ('SDR', 'canAccessRecepcao', false),
  ('SDR', 'canReadQRCode', false),
  ('SDR', 'canGenerateInvites', true),
  ('SDR', 'canAccessKanban', true),
  ('SDR', 'canEditAtendimentos', true),
  ('SDR', 'canDeleteAtendimentos', false),
  ('SDR', 'canViewProspeccao', true),
  ('SDR', 'canCreateProspeccao', false),
  ('SDR', 'canEditProspeccao', false),
  ('SDR', 'canDeleteProspeccao', false),
  ('SDR', 'canManageProspeccaoEquipes', false),
  ('SDR', 'canViewVendas', true),
  ('SDR', 'canCreateVendas', true),
  ('SDR', 'canEditVendas', false),
  ('SDR', 'canDeleteVendas', false),
  ('SDR', 'canManageUsers', false),
  ('SDR', 'canCreateUsers', false),
  ('SDR', 'canEditUsers', false),
  ('SDR', 'canDeleteUsers', false),
  ('SDR', 'canAccessAdminConfig', false),
  ('SDR', 'canAccessAdministracao', false),
  ('SDR', 'canAccessControleAcessos', false),
  ('SDR', 'canManageEmpresas', false),
  ('SDR', 'canEditEmpresas', false),
  ('SDR', 'canViewEmpresas', false),
  ('SDR', 'canAccessFinancialReports', false),
  ('SDR', 'canViewDashboard', true),
  ('SDR', 'canExportRelatorios', false),
  ('SDR', 'canAccessResultados', true),
  ('SDR', 'canViewMetricas', true),
  ('SDR', 'canSyncResultados', false),
  ('SDR', 'canAccessAcademy', false),
  ('SDR', 'canManageAcademy', false),
  ('SDR', 'canCreateTreinamentos', false),
  ('SDR', 'canEditTreinamentos', false),
  ('SDR', 'canDeleteTreinamentos', false),
  ('SDR', 'canAssignTreinamentos', false),
  ('SDR', 'canViewProgressoEquipe', false),
  ('SDR', 'canAccessConfiguracoes', false),
  ('SDR', 'canEditConfiguracoes', false),
  ('SDR', 'canManageDepartamentos', false),
  ('SDR', 'canManageMotivos', false),
  ('SDR', 'canManageOrigens', false),
  ('SDR', 'canManageTemperaturas', false),
  ('SDR', 'canManageWhatsApp', false),
  ('SDR', 'canManageMensagens', false),
  ('SDR', 'canManageDocumentos', false),
  ('SDR', 'canManageProdutos', false),
  ('SDR', 'canAccessPersonas', false),
  ('SDR', 'canCreatePersonas', false),
  ('SDR', 'canEditPersonas', false),
  ('SDR', 'canDeletePersonas', false),
  ('SDR', 'canAccessGatilhos', false),
  ('SDR', 'canCreateGatilhos', false),
  ('SDR', 'canEditGatilhos', false),
  ('SDR', 'canDeleteGatilhos', false),
  ('SDR', 'canAccessAPIs', false),
  ('SDR', 'canManageAPIs', false),
  ('SDR', 'canTestAPIs', false),
  ('SDR', 'canManageWebhooks', false),
  ('SDR', 'canAccessNotificacoes', true),
  ('SDR', 'canAccessMinhaConta', true),
  ('SDR', 'canAccessAjuda', true),
  ('SDR', 'canAccessRelatorios', true),
  ('Vendedor', 'canViewAuthenticator', false),
  ('Vendedor', 'canManageAuthenticator', false),
  ('Vendedor', 'canAssignAuthenticator', false),
  ('Vendedor', 'canViewAuditLogs', false),
  ('Vendedor', 'canViewControleAgentes', false),
  ('Vendedor', 'canCreateControleAgentes', false),
  ('Vendedor', 'canEditControleAgentes', false),
  ('Vendedor', 'canDeleteControleAgentes', false),
  ('Vendedor', 'canToggleControleAgentes', false),
  ('Vendedor', 'canAccessAgentesIA', false),
  ('Vendedor', 'canEditAgentesIA', false),
  ('Vendedor', 'canDeleteAgentesIA', false),
  ('Vendedor', 'canCreateAgentesIA', false),
  ('Vendedor', 'canManageInstancias', false),
  ('Vendedor', 'canViewVariaveis', false),
  ('Vendedor', 'canEditVariaveis', false),
  ('Vendedor', 'canManageCadencias', false),
  ('Vendedor', 'canManageFollowups', false),
  ('Vendedor', 'canManageIntegracoes', false),
  ('Vendedor', 'canViewTemplates', true),
  ('Vendedor', 'canCreateTemplates', false),
  ('Vendedor', 'canEditTemplates', false),
  ('Vendedor', 'canDeleteTemplates', false),
  ('Vendedor', 'canViewEventos', true),
  ('Vendedor', 'canCreateEventos', false),
  ('Vendedor', 'canEditEventos', false),
  ('Vendedor', 'canDeleteEventos', false),
  ('Vendedor', 'canManageEvents', true),
  ('Vendedor', 'canManageEventos', false),
  ('Vendedor', 'canCreateIALigacao', false),
  ('Vendedor', 'canDispararIALigacao', false),
  ('Vendedor', 'canToggleIALigacao', false),
  ('Vendedor', 'canViewIALigacaoLogs', false),
  ('Vendedor', 'canDispararEventos', false),
  ('Vendedor', 'canRedispararEventos', false),
  ('Vendedor', 'canAprovarCampanhas', false),
  ('Vendedor', 'canProgramarCampanhas', false),
  ('Vendedor', 'canViewClientes', true),
  ('Vendedor', 'canAddClientes', false),
  ('Vendedor', 'canEditClientes', false),
  ('Vendedor', 'canDeleteClientes', false),
  ('Vendedor', 'canImportClientes', false),
  ('Vendedor', 'canUploadBase', false),
  ('Vendedor', 'canEditContatos', true),
  ('Vendedor', 'canDeleteContatos', false),
  ('Vendedor', 'canValidarImportacao', false),
  ('Vendedor', 'canGovernancaDados', false),
  ('Vendedor', 'canAccessOptOutGlobal', false),
  ('Vendedor', 'canAccessRecepcao', false),
  ('Vendedor', 'canReadQRCode', false),
  ('Vendedor', 'canGenerateInvites', true),
  ('Vendedor', 'canAccessKanban', true),
  ('Vendedor', 'canEditAtendimentos', true),
  ('Vendedor', 'canDeleteAtendimentos', false),
  ('Vendedor', 'canViewProspeccao', true),
  ('Vendedor', 'canCreateProspeccao', false),
  ('Vendedor', 'canEditProspeccao', false),
  ('Vendedor', 'canDeleteProspeccao', false),
  ('Vendedor', 'canManageProspeccaoEquipes', false),
  ('Vendedor', 'canViewVendas', true),
  ('Vendedor', 'canCreateVendas', true),
  ('Vendedor', 'canEditVendas', false),
  ('Vendedor', 'canDeleteVendas', false),
  ('Vendedor', 'canManageUsers', false),
  ('Vendedor', 'canCreateUsers', false),
  ('Vendedor', 'canEditUsers', false),
  ('Vendedor', 'canDeleteUsers', false),
  ('Vendedor', 'canAccessAdminConfig', false),
  ('Vendedor', 'canAccessAdministracao', false),
  ('Vendedor', 'canAccessControleAcessos', false),
  ('Vendedor', 'canManageEmpresas', false),
  ('Vendedor', 'canEditEmpresas', false),
  ('Vendedor', 'canViewEmpresas', false),
  ('Vendedor', 'canAccessFinancialReports', false),
  ('Vendedor', 'canViewDashboard', true),
  ('Vendedor', 'canExportRelatorios', false),
  ('Vendedor', 'canAccessResultados', true),
  ('Vendedor', 'canViewMetricas', true),
  ('Vendedor', 'canSyncResultados', false),
  ('Vendedor', 'canAccessAcademy', false),
  ('Vendedor', 'canManageAcademy', false),
  ('Vendedor', 'canCreateTreinamentos', false),
  ('Vendedor', 'canEditTreinamentos', false),
  ('Vendedor', 'canDeleteTreinamentos', false),
  ('Vendedor', 'canAssignTreinamentos', false),
  ('Vendedor', 'canViewProgressoEquipe', false),
  ('Vendedor', 'canAccessConfiguracoes', false),
  ('Vendedor', 'canEditConfiguracoes', false),
  ('Vendedor', 'canManageDepartamentos', false),
  ('Vendedor', 'canManageMotivos', false),
  ('Vendedor', 'canManageOrigens', false),
  ('Vendedor', 'canManageTemperaturas', false),
  ('Vendedor', 'canManageWhatsApp', false),
  ('Vendedor', 'canManageMensagens', false),
  ('Vendedor', 'canManageDocumentos', false),
  ('Vendedor', 'canManageProdutos', false),
  ('Vendedor', 'canAccessPersonas', false),
  ('Vendedor', 'canCreatePersonas', false),
  ('Vendedor', 'canEditPersonas', false),
  ('Vendedor', 'canDeletePersonas', false),
  ('Vendedor', 'canAccessGatilhos', false),
  ('Vendedor', 'canCreateGatilhos', false),
  ('Vendedor', 'canEditGatilhos', false),
  ('Vendedor', 'canDeleteGatilhos', false),
  ('Vendedor', 'canAccessAPIs', false),
  ('Vendedor', 'canManageAPIs', false),
  ('Vendedor', 'canTestAPIs', false),
  ('Vendedor', 'canManageWebhooks', false),
  ('Vendedor', 'canAccessNotificacoes', true),
  ('Vendedor', 'canAccessMinhaConta', true),
  ('Vendedor', 'canAccessAjuda', true),
  ('Vendedor', 'canAccessRelatorios', true),
  ('CRM', 'canViewAuthenticator', false),
  ('CRM', 'canManageAuthenticator', false),
  ('CRM', 'canAssignAuthenticator', false),
  ('CRM', 'canViewAuditLogs', false),
  ('CRM', 'canViewControleAgentes', false),
  ('CRM', 'canCreateControleAgentes', false),
  ('CRM', 'canEditControleAgentes', false),
  ('CRM', 'canDeleteControleAgentes', false),
  ('CRM', 'canToggleControleAgentes', false),
  ('CRM', 'canAccessAgentesIA', false),
  ('CRM', 'canEditAgentesIA', false),
  ('CRM', 'canDeleteAgentesIA', false),
  ('CRM', 'canCreateAgentesIA', false),
  ('CRM', 'canManageInstancias', false),
  ('CRM', 'canViewVariaveis', false),
  ('CRM', 'canEditVariaveis', false),
  ('CRM', 'canManageCadencias', false),
  ('CRM', 'canManageFollowups', false),
  ('CRM', 'canManageIntegracoes', false),
  ('CRM', 'canViewTemplates', true),
  ('CRM', 'canCreateTemplates', true),
  ('CRM', 'canEditTemplates', true),
  ('CRM', 'canDeleteTemplates', false),
  ('CRM', 'canViewEventos', true),
  ('CRM', 'canCreateEventos', true),
  ('CRM', 'canEditEventos', true),
  ('CRM', 'canDeleteEventos', false),
  ('CRM', 'canManageEvents', true),
  ('CRM', 'canManageEventos', false),
  ('CRM', 'canCreateIALigacao', true),
  ('CRM', 'canDispararIALigacao', false),
  ('CRM', 'canToggleIALigacao', false),
  ('CRM', 'canViewIALigacaoLogs', false),
  ('CRM', 'canDispararEventos', true),
  ('CRM', 'canRedispararEventos', false),
  ('CRM', 'canAprovarCampanhas', true),
  ('CRM', 'canProgramarCampanhas', true),
  ('CRM', 'canViewClientes', true),
  ('CRM', 'canAddClientes', true),
  ('CRM', 'canEditClientes', true),
  ('CRM', 'canDeleteClientes', false),
  ('CRM', 'canImportClientes', true),
  ('CRM', 'canUploadBase', true),
  ('CRM', 'canEditContatos', true),
  ('CRM', 'canDeleteContatos', false),
  ('CRM', 'canValidarImportacao', true),
  ('CRM', 'canGovernancaDados', true),
  ('CRM', 'canAccessOptOutGlobal', true),
  ('CRM', 'canAccessRecepcao', true),
  ('CRM', 'canReadQRCode', false),
  ('CRM', 'canGenerateInvites', true),
  ('CRM', 'canAccessKanban', true),
  ('CRM', 'canEditAtendimentos', true),
  ('CRM', 'canDeleteAtendimentos', false),
  ('CRM', 'canViewProspeccao', true),
  ('CRM', 'canCreateProspeccao', true),
  ('CRM', 'canEditProspeccao', true),
  ('CRM', 'canDeleteProspeccao', false),
  ('CRM', 'canManageProspeccaoEquipes', true),
  ('CRM', 'canViewVendas', true),
  ('CRM', 'canCreateVendas', true),
  ('CRM', 'canEditVendas', true),
  ('CRM', 'canDeleteVendas', false),
  ('CRM', 'canManageUsers', false),
  ('CRM', 'canCreateUsers', true),
  ('CRM', 'canEditUsers', false),
  ('CRM', 'canDeleteUsers', false),
  ('CRM', 'canAccessAdminConfig', false),
  ('CRM', 'canAccessAdministracao', true),
  ('CRM', 'canAccessControleAcessos', false),
  ('CRM', 'canManageEmpresas', false),
  ('CRM', 'canEditEmpresas', false),
  ('CRM', 'canViewEmpresas', false),
  ('CRM', 'canAccessFinancialReports', false),
  ('CRM', 'canViewDashboard', true),
  ('CRM', 'canExportRelatorios', false),
  ('CRM', 'canAccessResultados', true),
  ('CRM', 'canViewMetricas', true),
  ('CRM', 'canSyncResultados', false),
  ('CRM', 'canAccessAcademy', false),
  ('CRM', 'canManageAcademy', false),
  ('CRM', 'canCreateTreinamentos', false),
  ('CRM', 'canEditTreinamentos', false),
  ('CRM', 'canDeleteTreinamentos', false),
  ('CRM', 'canAssignTreinamentos', false),
  ('CRM', 'canViewProgressoEquipe', false),
  ('CRM', 'canAccessConfiguracoes', false),
  ('CRM', 'canEditConfiguracoes', false),
  ('CRM', 'canManageDepartamentos', false),
  ('CRM', 'canManageMotivos', false),
  ('CRM', 'canManageOrigens', false),
  ('CRM', 'canManageTemperaturas', false),
  ('CRM', 'canManageWhatsApp', false),
  ('CRM', 'canManageMensagens', false),
  ('CRM', 'canManageDocumentos', false),
  ('CRM', 'canManageProdutos', false),
  ('CRM', 'canAccessPersonas', false),
  ('CRM', 'canCreatePersonas', false),
  ('CRM', 'canEditPersonas', false),
  ('CRM', 'canDeletePersonas', false),
  ('CRM', 'canAccessGatilhos', false),
  ('CRM', 'canCreateGatilhos', false),
  ('CRM', 'canEditGatilhos', false),
  ('CRM', 'canDeleteGatilhos', false),
  ('CRM', 'canAccessAPIs', false),
  ('CRM', 'canManageAPIs', false),
  ('CRM', 'canTestAPIs', false),
  ('CRM', 'canManageWebhooks', false),
  ('CRM', 'canAccessNotificacoes', true),
  ('CRM', 'canAccessMinhaConta', true),
  ('CRM', 'canAccessAjuda', true),
  ('CRM', 'canAccessRelatorios', true),
  ('Recepcionista', 'canViewAuthenticator', false),
  ('Recepcionista', 'canManageAuthenticator', false),
  ('Recepcionista', 'canAssignAuthenticator', false),
  ('Recepcionista', 'canViewAuditLogs', false),
  ('Recepcionista', 'canViewControleAgentes', false),
  ('Recepcionista', 'canCreateControleAgentes', false),
  ('Recepcionista', 'canEditControleAgentes', false),
  ('Recepcionista', 'canDeleteControleAgentes', false),
  ('Recepcionista', 'canToggleControleAgentes', false),
  ('Recepcionista', 'canAccessAgentesIA', false),
  ('Recepcionista', 'canEditAgentesIA', false),
  ('Recepcionista', 'canDeleteAgentesIA', false),
  ('Recepcionista', 'canCreateAgentesIA', false),
  ('Recepcionista', 'canManageInstancias', false),
  ('Recepcionista', 'canViewVariaveis', false),
  ('Recepcionista', 'canEditVariaveis', false),
  ('Recepcionista', 'canManageCadencias', false),
  ('Recepcionista', 'canManageFollowups', false),
  ('Recepcionista', 'canManageIntegracoes', false),
  ('Recepcionista', 'canViewTemplates', false),
  ('Recepcionista', 'canCreateTemplates', false),
  ('Recepcionista', 'canEditTemplates', false),
  ('Recepcionista', 'canDeleteTemplates', false),
  ('Recepcionista', 'canViewEventos', false),
  ('Recepcionista', 'canCreateEventos', false),
  ('Recepcionista', 'canEditEventos', false),
  ('Recepcionista', 'canDeleteEventos', false),
  ('Recepcionista', 'canManageEvents', false),
  ('Recepcionista', 'canManageEventos', false),
  ('Recepcionista', 'canCreateIALigacao', false),
  ('Recepcionista', 'canDispararIALigacao', false),
  ('Recepcionista', 'canToggleIALigacao', false),
  ('Recepcionista', 'canViewIALigacaoLogs', false),
  ('Recepcionista', 'canDispararEventos', false),
  ('Recepcionista', 'canRedispararEventos', false),
  ('Recepcionista', 'canAprovarCampanhas', false),
  ('Recepcionista', 'canProgramarCampanhas', false),
  ('Recepcionista', 'canViewClientes', true),
  ('Recepcionista', 'canAddClientes', false),
  ('Recepcionista', 'canEditClientes', false),
  ('Recepcionista', 'canDeleteClientes', false),
  ('Recepcionista', 'canImportClientes', false),
  ('Recepcionista', 'canUploadBase', false),
  ('Recepcionista', 'canEditContatos', false),
  ('Recepcionista', 'canDeleteContatos', false),
  ('Recepcionista', 'canValidarImportacao', false),
  ('Recepcionista', 'canGovernancaDados', false),
  ('Recepcionista', 'canAccessOptOutGlobal', false),
  ('Recepcionista', 'canAccessRecepcao', true),
  ('Recepcionista', 'canReadQRCode', true),
  ('Recepcionista', 'canGenerateInvites', false),
  ('Recepcionista', 'canAccessKanban', false),
  ('Recepcionista', 'canEditAtendimentos', false),
  ('Recepcionista', 'canDeleteAtendimentos', false),
  ('Recepcionista', 'canViewProspeccao', true),
  ('Recepcionista', 'canCreateProspeccao', false),
  ('Recepcionista', 'canEditProspeccao', false),
  ('Recepcionista', 'canDeleteProspeccao', false),
  ('Recepcionista', 'canManageProspeccaoEquipes', false),
  ('Recepcionista', 'canViewVendas', false),
  ('Recepcionista', 'canCreateVendas', false),
  ('Recepcionista', 'canEditVendas', false),
  ('Recepcionista', 'canDeleteVendas', false),
  ('Recepcionista', 'canManageUsers', false),
  ('Recepcionista', 'canCreateUsers', false),
  ('Recepcionista', 'canEditUsers', false),
  ('Recepcionista', 'canDeleteUsers', false),
  ('Recepcionista', 'canAccessAdminConfig', false),
  ('Recepcionista', 'canAccessAdministracao', false),
  ('Recepcionista', 'canAccessControleAcessos', false),
  ('Recepcionista', 'canManageEmpresas', false),
  ('Recepcionista', 'canEditEmpresas', false),
  ('Recepcionista', 'canViewEmpresas', false),
  ('Recepcionista', 'canAccessFinancialReports', false),
  ('Recepcionista', 'canViewDashboard', true),
  ('Recepcionista', 'canExportRelatorios', false),
  ('Recepcionista', 'canAccessResultados', false),
  ('Recepcionista', 'canViewMetricas', false),
  ('Recepcionista', 'canSyncResultados', false),
  ('Recepcionista', 'canAccessAcademy', false),
  ('Recepcionista', 'canManageAcademy', false),
  ('Recepcionista', 'canCreateTreinamentos', false),
  ('Recepcionista', 'canEditTreinamentos', false),
  ('Recepcionista', 'canDeleteTreinamentos', false),
  ('Recepcionista', 'canAssignTreinamentos', false),
  ('Recepcionista', 'canViewProgressoEquipe', false),
  ('Recepcionista', 'canAccessConfiguracoes', false),
  ('Recepcionista', 'canEditConfiguracoes', false),
  ('Recepcionista', 'canManageDepartamentos', false),
  ('Recepcionista', 'canManageMotivos', false),
  ('Recepcionista', 'canManageOrigens', false),
  ('Recepcionista', 'canManageTemperaturas', false),
  ('Recepcionista', 'canManageWhatsApp', false),
  ('Recepcionista', 'canManageMensagens', false),
  ('Recepcionista', 'canManageDocumentos', false),
  ('Recepcionista', 'canManageProdutos', false),
  ('Recepcionista', 'canAccessPersonas', false),
  ('Recepcionista', 'canCreatePersonas', false),
  ('Recepcionista', 'canEditPersonas', false),
  ('Recepcionista', 'canDeletePersonas', false),
  ('Recepcionista', 'canAccessGatilhos', false),
  ('Recepcionista', 'canCreateGatilhos', false),
  ('Recepcionista', 'canEditGatilhos', false),
  ('Recepcionista', 'canDeleteGatilhos', false),
  ('Recepcionista', 'canAccessAPIs', false),
  ('Recepcionista', 'canManageAPIs', false),
  ('Recepcionista', 'canTestAPIs', false),
  ('Recepcionista', 'canManageWebhooks', false),
  ('Recepcionista', 'canAccessNotificacoes', true),
  ('Recepcionista', 'canAccessMinhaConta', true),
  ('Recepcionista', 'canAccessAjuda', true),
  ('Recepcionista', 'canAccessRelatorios', false),
  ('Gerente de Leads', 'canViewAuthenticator', false),
  ('Gerente de Leads', 'canManageAuthenticator', false),
  ('Gerente de Leads', 'canAssignAuthenticator', false),
  ('Gerente de Leads', 'canViewAuditLogs', false),
  ('Gerente de Leads', 'canViewControleAgentes', false),
  ('Gerente de Leads', 'canCreateControleAgentes', false),
  ('Gerente de Leads', 'canEditControleAgentes', false),
  ('Gerente de Leads', 'canDeleteControleAgentes', false),
  ('Gerente de Leads', 'canToggleControleAgentes', false),
  ('Gerente de Leads', 'canAccessAgentesIA', false),
  ('Gerente de Leads', 'canEditAgentesIA', false),
  ('Gerente de Leads', 'canDeleteAgentesIA', false),
  ('Gerente de Leads', 'canCreateAgentesIA', false),
  ('Gerente de Leads', 'canManageInstancias', false),
  ('Gerente de Leads', 'canViewVariaveis', false),
  ('Gerente de Leads', 'canEditVariaveis', false),
  ('Gerente de Leads', 'canManageCadencias', false),
  ('Gerente de Leads', 'canManageFollowups', false),
  ('Gerente de Leads', 'canManageIntegracoes', false),
  ('Gerente de Leads', 'canViewTemplates', true),
  ('Gerente de Leads', 'canCreateTemplates', true),
  ('Gerente de Leads', 'canEditTemplates', true),
  ('Gerente de Leads', 'canDeleteTemplates', false),
  ('Gerente de Leads', 'canViewEventos', true),
  ('Gerente de Leads', 'canCreateEventos', true),
  ('Gerente de Leads', 'canEditEventos', true),
  ('Gerente de Leads', 'canDeleteEventos', false),
  ('Gerente de Leads', 'canManageEvents', true),
  ('Gerente de Leads', 'canManageEventos', false),
  ('Gerente de Leads', 'canCreateIALigacao', true),
  ('Gerente de Leads', 'canDispararIALigacao', false),
  ('Gerente de Leads', 'canToggleIALigacao', false),
  ('Gerente de Leads', 'canViewIALigacaoLogs', false),
  ('Gerente de Leads', 'canDispararEventos', true),
  ('Gerente de Leads', 'canRedispararEventos', false),
  ('Gerente de Leads', 'canAprovarCampanhas', false),
  ('Gerente de Leads', 'canProgramarCampanhas', true),
  ('Gerente de Leads', 'canViewClientes', true),
  ('Gerente de Leads', 'canAddClientes', false),
  ('Gerente de Leads', 'canEditClientes', true),
  ('Gerente de Leads', 'canDeleteClientes', false),
  ('Gerente de Leads', 'canImportClientes', false),
  ('Gerente de Leads', 'canUploadBase', false),
  ('Gerente de Leads', 'canEditContatos', true),
  ('Gerente de Leads', 'canDeleteContatos', false),
  ('Gerente de Leads', 'canValidarImportacao', false),
  ('Gerente de Leads', 'canGovernancaDados', false),
  ('Gerente de Leads', 'canAccessOptOutGlobal', false),
  ('Gerente de Leads', 'canAccessRecepcao', true),
  ('Gerente de Leads', 'canReadQRCode', false),
  ('Gerente de Leads', 'canGenerateInvites', true),
  ('Gerente de Leads', 'canAccessKanban', true),
  ('Gerente de Leads', 'canEditAtendimentos', true),
  ('Gerente de Leads', 'canDeleteAtendimentos', false),
  ('Gerente de Leads', 'canViewProspeccao', true),
  ('Gerente de Leads', 'canCreateProspeccao', true),
  ('Gerente de Leads', 'canEditProspeccao', true),
  ('Gerente de Leads', 'canDeleteProspeccao', false),
  ('Gerente de Leads', 'canManageProspeccaoEquipes', true),
  ('Gerente de Leads', 'canViewVendas', true),
  ('Gerente de Leads', 'canCreateVendas', true),
  ('Gerente de Leads', 'canEditVendas', true),
  ('Gerente de Leads', 'canDeleteVendas', false),
  ('Gerente de Leads', 'canManageUsers', false),
  ('Gerente de Leads', 'canCreateUsers', true),
  ('Gerente de Leads', 'canEditUsers', true),
  ('Gerente de Leads', 'canDeleteUsers', false),
  ('Gerente de Leads', 'canAccessAdminConfig', false),
  ('Gerente de Leads', 'canAccessAdministracao', true),
  ('Gerente de Leads', 'canAccessControleAcessos', false),
  ('Gerente de Leads', 'canManageEmpresas', false),
  ('Gerente de Leads', 'canEditEmpresas', false),
  ('Gerente de Leads', 'canViewEmpresas', true),
  ('Gerente de Leads', 'canAccessFinancialReports', false),
  ('Gerente de Leads', 'canViewDashboard', true),
  ('Gerente de Leads', 'canExportRelatorios', false),
  ('Gerente de Leads', 'canAccessResultados', true),
  ('Gerente de Leads', 'canViewMetricas', true),
  ('Gerente de Leads', 'canSyncResultados', false),
  ('Gerente de Leads', 'canAccessAcademy', false),
  ('Gerente de Leads', 'canManageAcademy', true),
  ('Gerente de Leads', 'canCreateTreinamentos', false),
  ('Gerente de Leads', 'canEditTreinamentos', false),
  ('Gerente de Leads', 'canDeleteTreinamentos', false),
  ('Gerente de Leads', 'canAssignTreinamentos', true),
  ('Gerente de Leads', 'canViewProgressoEquipe', true),
  ('Gerente de Leads', 'canAccessConfiguracoes', false),
  ('Gerente de Leads', 'canEditConfiguracoes', false),
  ('Gerente de Leads', 'canManageDepartamentos', false),
  ('Gerente de Leads', 'canManageMotivos', false),
  ('Gerente de Leads', 'canManageOrigens', false),
  ('Gerente de Leads', 'canManageTemperaturas', false),
  ('Gerente de Leads', 'canManageWhatsApp', false),
  ('Gerente de Leads', 'canManageMensagens', false),
  ('Gerente de Leads', 'canManageDocumentos', false),
  ('Gerente de Leads', 'canManageProdutos', false),
  ('Gerente de Leads', 'canAccessPersonas', false),
  ('Gerente de Leads', 'canCreatePersonas', false),
  ('Gerente de Leads', 'canEditPersonas', false),
  ('Gerente de Leads', 'canDeletePersonas', false),
  ('Gerente de Leads', 'canAccessGatilhos', false),
  ('Gerente de Leads', 'canCreateGatilhos', false),
  ('Gerente de Leads', 'canEditGatilhos', false),
  ('Gerente de Leads', 'canDeleteGatilhos', false),
  ('Gerente de Leads', 'canAccessAPIs', false),
  ('Gerente de Leads', 'canManageAPIs', false),
  ('Gerente de Leads', 'canTestAPIs', false),
  ('Gerente de Leads', 'canManageWebhooks', false),
  ('Gerente de Leads', 'canAccessNotificacoes', true),
  ('Gerente de Leads', 'canAccessMinhaConta', true),
  ('Gerente de Leads', 'canAccessAjuda', true),
  ('Gerente de Leads', 'canAccessRelatorios', true),
  ('Gerente de Loja', 'canViewAuthenticator', false),
  ('Gerente de Loja', 'canManageAuthenticator', false),
  ('Gerente de Loja', 'canAssignAuthenticator', false),
  ('Gerente de Loja', 'canViewAuditLogs', false),
  ('Gerente de Loja', 'canViewControleAgentes', false),
  ('Gerente de Loja', 'canCreateControleAgentes', false),
  ('Gerente de Loja', 'canEditControleAgentes', false),
  ('Gerente de Loja', 'canDeleteControleAgentes', false),
  ('Gerente de Loja', 'canToggleControleAgentes', false),
  ('Gerente de Loja', 'canAccessAgentesIA', false),
  ('Gerente de Loja', 'canEditAgentesIA', false),
  ('Gerente de Loja', 'canDeleteAgentesIA', false),
  ('Gerente de Loja', 'canCreateAgentesIA', false),
  ('Gerente de Loja', 'canManageInstancias', false),
  ('Gerente de Loja', 'canViewVariaveis', false),
  ('Gerente de Loja', 'canEditVariaveis', false),
  ('Gerente de Loja', 'canManageCadencias', false),
  ('Gerente de Loja', 'canManageFollowups', false),
  ('Gerente de Loja', 'canManageIntegracoes', false),
  ('Gerente de Loja', 'canViewTemplates', true),
  ('Gerente de Loja', 'canCreateTemplates', true),
  ('Gerente de Loja', 'canEditTemplates', true),
  ('Gerente de Loja', 'canDeleteTemplates', false),
  ('Gerente de Loja', 'canViewEventos', true),
  ('Gerente de Loja', 'canCreateEventos', true),
  ('Gerente de Loja', 'canEditEventos', true),
  ('Gerente de Loja', 'canDeleteEventos', false),
  ('Gerente de Loja', 'canManageEvents', true),
  ('Gerente de Loja', 'canManageEventos', false),
  ('Gerente de Loja', 'canCreateIALigacao', true),
  ('Gerente de Loja', 'canDispararIALigacao', false),
  ('Gerente de Loja', 'canToggleIALigacao', false),
  ('Gerente de Loja', 'canViewIALigacaoLogs', false),
  ('Gerente de Loja', 'canDispararEventos', true),
  ('Gerente de Loja', 'canRedispararEventos', false),
  ('Gerente de Loja', 'canAprovarCampanhas', false),
  ('Gerente de Loja', 'canProgramarCampanhas', true),
  ('Gerente de Loja', 'canViewClientes', true),
  ('Gerente de Loja', 'canAddClientes', false),
  ('Gerente de Loja', 'canEditClientes', true),
  ('Gerente de Loja', 'canDeleteClientes', false),
  ('Gerente de Loja', 'canImportClientes', false),
  ('Gerente de Loja', 'canUploadBase', false),
  ('Gerente de Loja', 'canEditContatos', true),
  ('Gerente de Loja', 'canDeleteContatos', false),
  ('Gerente de Loja', 'canValidarImportacao', false),
  ('Gerente de Loja', 'canGovernancaDados', false),
  ('Gerente de Loja', 'canAccessOptOutGlobal', false),
  ('Gerente de Loja', 'canAccessRecepcao', true),
  ('Gerente de Loja', 'canReadQRCode', false),
  ('Gerente de Loja', 'canGenerateInvites', true),
  ('Gerente de Loja', 'canAccessKanban', true),
  ('Gerente de Loja', 'canEditAtendimentos', true),
  ('Gerente de Loja', 'canDeleteAtendimentos', false),
  ('Gerente de Loja', 'canViewProspeccao', true),
  ('Gerente de Loja', 'canCreateProspeccao', true),
  ('Gerente de Loja', 'canEditProspeccao', true),
  ('Gerente de Loja', 'canDeleteProspeccao', false),
  ('Gerente de Loja', 'canManageProspeccaoEquipes', true),
  ('Gerente de Loja', 'canViewVendas', true),
  ('Gerente de Loja', 'canCreateVendas', true),
  ('Gerente de Loja', 'canEditVendas', true),
  ('Gerente de Loja', 'canDeleteVendas', false),
  ('Gerente de Loja', 'canManageUsers', false),
  ('Gerente de Loja', 'canCreateUsers', true),
  ('Gerente de Loja', 'canEditUsers', true),
  ('Gerente de Loja', 'canDeleteUsers', false),
  ('Gerente de Loja', 'canAccessAdminConfig', false),
  ('Gerente de Loja', 'canAccessAdministracao', true),
  ('Gerente de Loja', 'canAccessControleAcessos', false),
  ('Gerente de Loja', 'canManageEmpresas', false),
  ('Gerente de Loja', 'canEditEmpresas', false),
  ('Gerente de Loja', 'canViewEmpresas', true),
  ('Gerente de Loja', 'canAccessFinancialReports', false),
  ('Gerente de Loja', 'canViewDashboard', true),
  ('Gerente de Loja', 'canExportRelatorios', false),
  ('Gerente de Loja', 'canAccessResultados', true),
  ('Gerente de Loja', 'canViewMetricas', true),
  ('Gerente de Loja', 'canSyncResultados', false),
  ('Gerente de Loja', 'canAccessAcademy', false),
  ('Gerente de Loja', 'canManageAcademy', true),
  ('Gerente de Loja', 'canCreateTreinamentos', false),
  ('Gerente de Loja', 'canEditTreinamentos', false),
  ('Gerente de Loja', 'canDeleteTreinamentos', false),
  ('Gerente de Loja', 'canAssignTreinamentos', true),
  ('Gerente de Loja', 'canViewProgressoEquipe', true),
  ('Gerente de Loja', 'canAccessConfiguracoes', false),
  ('Gerente de Loja', 'canEditConfiguracoes', false),
  ('Gerente de Loja', 'canManageDepartamentos', false),
  ('Gerente de Loja', 'canManageMotivos', false),
  ('Gerente de Loja', 'canManageOrigens', false),
  ('Gerente de Loja', 'canManageTemperaturas', false),
  ('Gerente de Loja', 'canManageWhatsApp', false),
  ('Gerente de Loja', 'canManageMensagens', false),
  ('Gerente de Loja', 'canManageDocumentos', false),
  ('Gerente de Loja', 'canManageProdutos', false),
  ('Gerente de Loja', 'canAccessPersonas', false),
  ('Gerente de Loja', 'canCreatePersonas', false),
  ('Gerente de Loja', 'canEditPersonas', false),
  ('Gerente de Loja', 'canDeletePersonas', false),
  ('Gerente de Loja', 'canAccessGatilhos', false),
  ('Gerente de Loja', 'canCreateGatilhos', false),
  ('Gerente de Loja', 'canEditGatilhos', false),
  ('Gerente de Loja', 'canDeleteGatilhos', false),
  ('Gerente de Loja', 'canAccessAPIs', false),
  ('Gerente de Loja', 'canManageAPIs', false),
  ('Gerente de Loja', 'canTestAPIs', false),
  ('Gerente de Loja', 'canManageWebhooks', false),
  ('Gerente de Loja', 'canAccessNotificacoes', true),
  ('Gerente de Loja', 'canAccessMinhaConta', true),
  ('Gerente de Loja', 'canAccessAjuda', true),
  ('Gerente de Loja', 'canAccessRelatorios', true),
  ('Coordenadora de Leads', 'canViewAuthenticator', false),
  ('Coordenadora de Leads', 'canManageAuthenticator', false),
  ('Coordenadora de Leads', 'canAssignAuthenticator', false),
  ('Coordenadora de Leads', 'canViewAuditLogs', false),
  ('Coordenadora de Leads', 'canViewControleAgentes', false),
  ('Coordenadora de Leads', 'canCreateControleAgentes', false),
  ('Coordenadora de Leads', 'canEditControleAgentes', false),
  ('Coordenadora de Leads', 'canDeleteControleAgentes', false),
  ('Coordenadora de Leads', 'canToggleControleAgentes', false),
  ('Coordenadora de Leads', 'canAccessAgentesIA', false),
  ('Coordenadora de Leads', 'canEditAgentesIA', false),
  ('Coordenadora de Leads', 'canDeleteAgentesIA', false),
  ('Coordenadora de Leads', 'canCreateAgentesIA', false),
  ('Coordenadora de Leads', 'canManageInstancias', false),
  ('Coordenadora de Leads', 'canViewVariaveis', false),
  ('Coordenadora de Leads', 'canEditVariaveis', false),
  ('Coordenadora de Leads', 'canManageCadencias', false),
  ('Coordenadora de Leads', 'canManageFollowups', false),
  ('Coordenadora de Leads', 'canManageIntegracoes', false),
  ('Coordenadora de Leads', 'canViewTemplates', true),
  ('Coordenadora de Leads', 'canCreateTemplates', true),
  ('Coordenadora de Leads', 'canEditTemplates', true),
  ('Coordenadora de Leads', 'canDeleteTemplates', false),
  ('Coordenadora de Leads', 'canViewEventos', true),
  ('Coordenadora de Leads', 'canCreateEventos', true),
  ('Coordenadora de Leads', 'canEditEventos', true),
  ('Coordenadora de Leads', 'canDeleteEventos', false),
  ('Coordenadora de Leads', 'canManageEvents', true),
  ('Coordenadora de Leads', 'canManageEventos', false),
  ('Coordenadora de Leads', 'canCreateIALigacao', true),
  ('Coordenadora de Leads', 'canDispararIALigacao', false),
  ('Coordenadora de Leads', 'canToggleIALigacao', false),
  ('Coordenadora de Leads', 'canViewIALigacaoLogs', false),
  ('Coordenadora de Leads', 'canDispararEventos', true),
  ('Coordenadora de Leads', 'canRedispararEventos', false),
  ('Coordenadora de Leads', 'canAprovarCampanhas', false),
  ('Coordenadora de Leads', 'canProgramarCampanhas', true),
  ('Coordenadora de Leads', 'canViewClientes', true),
  ('Coordenadora de Leads', 'canAddClientes', false),
  ('Coordenadora de Leads', 'canEditClientes', true),
  ('Coordenadora de Leads', 'canDeleteClientes', false),
  ('Coordenadora de Leads', 'canImportClientes', false),
  ('Coordenadora de Leads', 'canUploadBase', false),
  ('Coordenadora de Leads', 'canEditContatos', true),
  ('Coordenadora de Leads', 'canDeleteContatos', false),
  ('Coordenadora de Leads', 'canValidarImportacao', false),
  ('Coordenadora de Leads', 'canGovernancaDados', false),
  ('Coordenadora de Leads', 'canAccessOptOutGlobal', false),
  ('Coordenadora de Leads', 'canAccessRecepcao', true),
  ('Coordenadora de Leads', 'canReadQRCode', false),
  ('Coordenadora de Leads', 'canGenerateInvites', true),
  ('Coordenadora de Leads', 'canAccessKanban', true),
  ('Coordenadora de Leads', 'canEditAtendimentos', true),
  ('Coordenadora de Leads', 'canDeleteAtendimentos', false),
  ('Coordenadora de Leads', 'canViewProspeccao', true),
  ('Coordenadora de Leads', 'canCreateProspeccao', true),
  ('Coordenadora de Leads', 'canEditProspeccao', true),
  ('Coordenadora de Leads', 'canDeleteProspeccao', false),
  ('Coordenadora de Leads', 'canManageProspeccaoEquipes', true),
  ('Coordenadora de Leads', 'canViewVendas', true),
  ('Coordenadora de Leads', 'canCreateVendas', true),
  ('Coordenadora de Leads', 'canEditVendas', true),
  ('Coordenadora de Leads', 'canDeleteVendas', false),
  ('Coordenadora de Leads', 'canManageUsers', false),
  ('Coordenadora de Leads', 'canCreateUsers', true),
  ('Coordenadora de Leads', 'canEditUsers', true),
  ('Coordenadora de Leads', 'canDeleteUsers', false),
  ('Coordenadora de Leads', 'canAccessAdminConfig', false),
  ('Coordenadora de Leads', 'canAccessAdministracao', true),
  ('Coordenadora de Leads', 'canAccessControleAcessos', false),
  ('Coordenadora de Leads', 'canManageEmpresas', false),
  ('Coordenadora de Leads', 'canEditEmpresas', false),
  ('Coordenadora de Leads', 'canViewEmpresas', true),
  ('Coordenadora de Leads', 'canAccessFinancialReports', false),
  ('Coordenadora de Leads', 'canViewDashboard', true),
  ('Coordenadora de Leads', 'canExportRelatorios', false),
  ('Coordenadora de Leads', 'canAccessResultados', true),
  ('Coordenadora de Leads', 'canViewMetricas', true),
  ('Coordenadora de Leads', 'canSyncResultados', false),
  ('Coordenadora de Leads', 'canAccessAcademy', false),
  ('Coordenadora de Leads', 'canManageAcademy', true),
  ('Coordenadora de Leads', 'canCreateTreinamentos', false),
  ('Coordenadora de Leads', 'canEditTreinamentos', false),
  ('Coordenadora de Leads', 'canDeleteTreinamentos', false),
  ('Coordenadora de Leads', 'canAssignTreinamentos', true),
  ('Coordenadora de Leads', 'canViewProgressoEquipe', true),
  ('Coordenadora de Leads', 'canAccessConfiguracoes', false),
  ('Coordenadora de Leads', 'canEditConfiguracoes', false),
  ('Coordenadora de Leads', 'canManageDepartamentos', false),
  ('Coordenadora de Leads', 'canManageMotivos', false),
  ('Coordenadora de Leads', 'canManageOrigens', false),
  ('Coordenadora de Leads', 'canManageTemperaturas', false),
  ('Coordenadora de Leads', 'canManageWhatsApp', false),
  ('Coordenadora de Leads', 'canManageMensagens', false),
  ('Coordenadora de Leads', 'canManageDocumentos', false),
  ('Coordenadora de Leads', 'canManageProdutos', false),
  ('Coordenadora de Leads', 'canAccessPersonas', false),
  ('Coordenadora de Leads', 'canCreatePersonas', false),
  ('Coordenadora de Leads', 'canEditPersonas', false),
  ('Coordenadora de Leads', 'canDeletePersonas', false),
  ('Coordenadora de Leads', 'canAccessGatilhos', false),
  ('Coordenadora de Leads', 'canCreateGatilhos', false),
  ('Coordenadora de Leads', 'canEditGatilhos', false),
  ('Coordenadora de Leads', 'canDeleteGatilhos', false),
  ('Coordenadora de Leads', 'canAccessAPIs', false),
  ('Coordenadora de Leads', 'canManageAPIs', false),
  ('Coordenadora de Leads', 'canTestAPIs', false),
  ('Coordenadora de Leads', 'canManageWebhooks', false),
  ('Coordenadora de Leads', 'canAccessNotificacoes', true),
  ('Coordenadora de Leads', 'canAccessMinhaConta', true),
  ('Coordenadora de Leads', 'canAccessAjuda', true),
  ('Coordenadora de Leads', 'canAccessRelatorios', true),
  ('Diretor', 'canViewAuthenticator', false),
  ('Diretor', 'canManageAuthenticator', false),
  ('Diretor', 'canAssignAuthenticator', false),
  ('Diretor', 'canViewAuditLogs', false),
  ('Diretor', 'canViewControleAgentes', false),
  ('Diretor', 'canCreateControleAgentes', false),
  ('Diretor', 'canEditControleAgentes', false),
  ('Diretor', 'canDeleteControleAgentes', false),
  ('Diretor', 'canToggleControleAgentes', false),
  ('Diretor', 'canAccessAgentesIA', false),
  ('Diretor', 'canEditAgentesIA', false),
  ('Diretor', 'canDeleteAgentesIA', false),
  ('Diretor', 'canCreateAgentesIA', false),
  ('Diretor', 'canManageInstancias', false),
  ('Diretor', 'canViewVariaveis', false),
  ('Diretor', 'canEditVariaveis', false),
  ('Diretor', 'canManageCadencias', false),
  ('Diretor', 'canManageFollowups', false),
  ('Diretor', 'canManageIntegracoes', false),
  ('Diretor', 'canViewTemplates', true),
  ('Diretor', 'canCreateTemplates', false),
  ('Diretor', 'canEditTemplates', false),
  ('Diretor', 'canDeleteTemplates', false),
  ('Diretor', 'canViewEventos', true),
  ('Diretor', 'canCreateEventos', false),
  ('Diretor', 'canEditEventos', false),
  ('Diretor', 'canDeleteEventos', false),
  ('Diretor', 'canManageEvents', true),
  ('Diretor', 'canManageEventos', false),
  ('Diretor', 'canCreateIALigacao', false),
  ('Diretor', 'canDispararIALigacao', false),
  ('Diretor', 'canToggleIALigacao', false),
  ('Diretor', 'canViewIALigacaoLogs', false),
  ('Diretor', 'canDispararEventos', false),
  ('Diretor', 'canRedispararEventos', false),
  ('Diretor', 'canAprovarCampanhas', false),
  ('Diretor', 'canProgramarCampanhas', false),
  ('Diretor', 'canViewClientes', true),
  ('Diretor', 'canAddClientes', false),
  ('Diretor', 'canEditClientes', false),
  ('Diretor', 'canDeleteClientes', false),
  ('Diretor', 'canImportClientes', false),
  ('Diretor', 'canUploadBase', false),
  ('Diretor', 'canEditContatos', true),
  ('Diretor', 'canDeleteContatos', false),
  ('Diretor', 'canValidarImportacao', false),
  ('Diretor', 'canGovernancaDados', false),
  ('Diretor', 'canAccessOptOutGlobal', false),
  ('Diretor', 'canAccessRecepcao', false),
  ('Diretor', 'canReadQRCode', false),
  ('Diretor', 'canGenerateInvites', true),
  ('Diretor', 'canAccessKanban', true),
  ('Diretor', 'canEditAtendimentos', true),
  ('Diretor', 'canDeleteAtendimentos', false),
  ('Diretor', 'canViewProspeccao', true),
  ('Diretor', 'canCreateProspeccao', false),
  ('Diretor', 'canEditProspeccao', false),
  ('Diretor', 'canDeleteProspeccao', false),
  ('Diretor', 'canManageProspeccaoEquipes', false),
  ('Diretor', 'canViewVendas', true),
  ('Diretor', 'canCreateVendas', true),
  ('Diretor', 'canEditVendas', false),
  ('Diretor', 'canDeleteVendas', false),
  ('Diretor', 'canManageUsers', false),
  ('Diretor', 'canCreateUsers', false),
  ('Diretor', 'canEditUsers', false),
  ('Diretor', 'canDeleteUsers', false),
  ('Diretor', 'canAccessAdminConfig', false),
  ('Diretor', 'canAccessAdministracao', false),
  ('Diretor', 'canAccessControleAcessos', false),
  ('Diretor', 'canManageEmpresas', false),
  ('Diretor', 'canEditEmpresas', false),
  ('Diretor', 'canViewEmpresas', true),
  ('Diretor', 'canAccessFinancialReports', true),
  ('Diretor', 'canViewDashboard', true),
  ('Diretor', 'canExportRelatorios', true),
  ('Diretor', 'canAccessResultados', true),
  ('Diretor', 'canViewMetricas', true),
  ('Diretor', 'canSyncResultados', false),
  ('Diretor', 'canAccessAcademy', false),
  ('Diretor', 'canManageAcademy', true),
  ('Diretor', 'canCreateTreinamentos', false),
  ('Diretor', 'canEditTreinamentos', false),
  ('Diretor', 'canDeleteTreinamentos', false),
  ('Diretor', 'canAssignTreinamentos', true),
  ('Diretor', 'canViewProgressoEquipe', true),
  ('Diretor', 'canAccessConfiguracoes', false),
  ('Diretor', 'canEditConfiguracoes', false),
  ('Diretor', 'canManageDepartamentos', false),
  ('Diretor', 'canManageMotivos', false),
  ('Diretor', 'canManageOrigens', false),
  ('Diretor', 'canManageTemperaturas', false),
  ('Diretor', 'canManageWhatsApp', false),
  ('Diretor', 'canManageMensagens', false),
  ('Diretor', 'canManageDocumentos', false),
  ('Diretor', 'canManageProdutos', false),
  ('Diretor', 'canAccessPersonas', false),
  ('Diretor', 'canCreatePersonas', false),
  ('Diretor', 'canEditPersonas', false),
  ('Diretor', 'canDeletePersonas', false),
  ('Diretor', 'canAccessGatilhos', false),
  ('Diretor', 'canCreateGatilhos', false),
  ('Diretor', 'canEditGatilhos', false),
  ('Diretor', 'canDeleteGatilhos', false),
  ('Diretor', 'canAccessAPIs', false),
  ('Diretor', 'canManageAPIs', false),
  ('Diretor', 'canTestAPIs', false),
  ('Diretor', 'canManageWebhooks', false),
  ('Diretor', 'canAccessNotificacoes', true),
  ('Diretor', 'canAccessMinhaConta', true),
  ('Diretor', 'canAccessAjuda', true),
  ('Diretor', 'canAccessRelatorios', true),
  ('TI', 'canViewAuthenticator', false),
  ('TI', 'canManageAuthenticator', false),
  ('TI', 'canAssignAuthenticator', false),
  ('TI', 'canViewAuditLogs', false),
  ('TI', 'canViewControleAgentes', true),
  ('TI', 'canCreateControleAgentes', true),
  ('TI', 'canEditControleAgentes', true),
  ('TI', 'canDeleteControleAgentes', true),
  ('TI', 'canToggleControleAgentes', true),
  ('TI', 'canAccessAgentesIA', true),
  ('TI', 'canEditAgentesIA', true),
  ('TI', 'canDeleteAgentesIA', true),
  ('TI', 'canCreateAgentesIA', true),
  ('TI', 'canManageInstancias', true),
  ('TI', 'canViewVariaveis', true),
  ('TI', 'canEditVariaveis', true),
  ('TI', 'canManageCadencias', true),
  ('TI', 'canManageFollowups', true),
  ('TI', 'canManageIntegracoes', true),
  ('TI', 'canViewTemplates', true),
  ('TI', 'canCreateTemplates', true),
  ('TI', 'canEditTemplates', true),
  ('TI', 'canDeleteTemplates', true),
  ('TI', 'canViewEventos', true),
  ('TI', 'canCreateEventos', true),
  ('TI', 'canEditEventos', true),
  ('TI', 'canDeleteEventos', true),
  ('TI', 'canManageEvents', true),
  ('TI', 'canManageEventos', true),
  ('TI', 'canCreateIALigacao', true),
  ('TI', 'canDispararIALigacao', false),
  ('TI', 'canToggleIALigacao', true),
  ('TI', 'canViewIALigacaoLogs', true),
  ('TI', 'canDispararEventos', true),
  ('TI', 'canRedispararEventos', true),
  ('TI', 'canAprovarCampanhas', true),
  ('TI', 'canProgramarCampanhas', true),
  ('TI', 'canViewClientes', true),
  ('TI', 'canAddClientes', false),
  ('TI', 'canEditClientes', false),
  ('TI', 'canDeleteClientes', true),
  ('TI', 'canImportClientes', false),
  ('TI', 'canUploadBase', false),
  ('TI', 'canEditContatos', true),
  ('TI', 'canDeleteContatos', true),
  ('TI', 'canValidarImportacao', true),
  ('TI', 'canGovernancaDados', true),
  ('TI', 'canAccessOptOutGlobal', true),
  ('TI', 'canAccessRecepcao', false),
  ('TI', 'canReadQRCode', false),
  ('TI', 'canGenerateInvites', true),
  ('TI', 'canAccessKanban', true),
  ('TI', 'canEditAtendimentos', true),
  ('TI', 'canDeleteAtendimentos', true),
  ('TI', 'canViewProspeccao', true),
  ('TI', 'canCreateProspeccao', true),
  ('TI', 'canEditProspeccao', true),
  ('TI', 'canDeleteProspeccao', true),
  ('TI', 'canManageProspeccaoEquipes', true),
  ('TI', 'canViewVendas', true),
  ('TI', 'canCreateVendas', true),
  ('TI', 'canEditVendas', true),
  ('TI', 'canDeleteVendas', true),
  ('TI', 'canManageUsers', true),
  ('TI', 'canCreateUsers', true),
  ('TI', 'canEditUsers', true),
  ('TI', 'canDeleteUsers', true),
  ('TI', 'canAccessAdminConfig', true),
  ('TI', 'canAccessAdministracao', false),
  ('TI', 'canAccessControleAcessos', false),
  ('TI', 'canManageEmpresas', true),
  ('TI', 'canEditEmpresas', false),
  ('TI', 'canViewEmpresas', true),
  ('TI', 'canAccessFinancialReports', true),
  ('TI', 'canViewDashboard', true),
  ('TI', 'canExportRelatorios', true),
  ('TI', 'canAccessResultados', true),
  ('TI', 'canViewMetricas', true),
  ('TI', 'canSyncResultados', true),
  ('TI', 'canAccessAcademy', true),
  ('TI', 'canManageAcademy', true),
  ('TI', 'canCreateTreinamentos', true),
  ('TI', 'canEditTreinamentos', true),
  ('TI', 'canDeleteTreinamentos', true),
  ('TI', 'canAssignTreinamentos', true),
  ('TI', 'canViewProgressoEquipe', true),
  ('TI', 'canAccessConfiguracoes', true),
  ('TI', 'canEditConfiguracoes', true),
  ('TI', 'canManageDepartamentos', true),
  ('TI', 'canManageMotivos', true),
  ('TI', 'canManageOrigens', true),
  ('TI', 'canManageTemperaturas', true),
  ('TI', 'canManageWhatsApp', true),
  ('TI', 'canManageMensagens', true),
  ('TI', 'canManageDocumentos', true),
  ('TI', 'canManageProdutos', true),
  ('TI', 'canAccessPersonas', true),
  ('TI', 'canCreatePersonas', true),
  ('TI', 'canEditPersonas', true),
  ('TI', 'canDeletePersonas', true),
  ('TI', 'canAccessGatilhos', true),
  ('TI', 'canCreateGatilhos', true),
  ('TI', 'canEditGatilhos', true),
  ('TI', 'canDeleteGatilhos', true),
  ('TI', 'canAccessAPIs', true),
  ('TI', 'canManageAPIs', true),
  ('TI', 'canTestAPIs', true),
  ('TI', 'canManageWebhooks', true),
  ('TI', 'canAccessNotificacoes', true),
  ('TI', 'canAccessMinhaConta', true),
  ('TI', 'canAccessAjuda', true),
  ('TI', 'canAccessRelatorios', true),
  ('Administrador', 'canViewAuthenticator', false),
  ('Administrador', 'canManageAuthenticator', false),
  ('Administrador', 'canAssignAuthenticator', false),
  ('Administrador', 'canViewAuditLogs', false),
  ('Administrador', 'canViewControleAgentes', true),
  ('Administrador', 'canCreateControleAgentes', true),
  ('Administrador', 'canEditControleAgentes', true),
  ('Administrador', 'canDeleteControleAgentes', true),
  ('Administrador', 'canToggleControleAgentes', true),
  ('Administrador', 'canAccessAgentesIA', true),
  ('Administrador', 'canEditAgentesIA', true),
  ('Administrador', 'canDeleteAgentesIA', true),
  ('Administrador', 'canCreateAgentesIA', true),
  ('Administrador', 'canManageInstancias', true),
  ('Administrador', 'canViewVariaveis', true),
  ('Administrador', 'canEditVariaveis', true),
  ('Administrador', 'canManageCadencias', true),
  ('Administrador', 'canManageFollowups', true),
  ('Administrador', 'canManageIntegracoes', true),
  ('Administrador', 'canViewTemplates', true),
  ('Administrador', 'canCreateTemplates', true),
  ('Administrador', 'canEditTemplates', true),
  ('Administrador', 'canDeleteTemplates', true),
  ('Administrador', 'canViewEventos', true),
  ('Administrador', 'canCreateEventos', true),
  ('Administrador', 'canEditEventos', true),
  ('Administrador', 'canDeleteEventos', true),
  ('Administrador', 'canManageEvents', true),
  ('Administrador', 'canManageEventos', true),
  ('Administrador', 'canCreateIALigacao', true),
  ('Administrador', 'canDispararIALigacao', true),
  ('Administrador', 'canToggleIALigacao', true),
  ('Administrador', 'canViewIALigacaoLogs', true),
  ('Administrador', 'canDispararEventos', true),
  ('Administrador', 'canRedispararEventos', true),
  ('Administrador', 'canAprovarCampanhas', true),
  ('Administrador', 'canProgramarCampanhas', true),
  ('Administrador', 'canViewClientes', true),
  ('Administrador', 'canAddClientes', true),
  ('Administrador', 'canEditClientes', true),
  ('Administrador', 'canDeleteClientes', true),
  ('Administrador', 'canImportClientes', false),
  ('Administrador', 'canUploadBase', true),
  ('Administrador', 'canEditContatos', true),
  ('Administrador', 'canDeleteContatos', true),
  ('Administrador', 'canValidarImportacao', true),
  ('Administrador', 'canGovernancaDados', true),
  ('Administrador', 'canAccessOptOutGlobal', true),
  ('Administrador', 'canAccessRecepcao', true),
  ('Administrador', 'canReadQRCode', true),
  ('Administrador', 'canGenerateInvites', true),
  ('Administrador', 'canAccessKanban', true),
  ('Administrador', 'canEditAtendimentos', true),
  ('Administrador', 'canDeleteAtendimentos', true),
  ('Administrador', 'canViewProspeccao', true),
  ('Administrador', 'canCreateProspeccao', true),
  ('Administrador', 'canEditProspeccao', true),
  ('Administrador', 'canDeleteProspeccao', true),
  ('Administrador', 'canManageProspeccaoEquipes', true),
  ('Administrador', 'canViewVendas', true),
  ('Administrador', 'canCreateVendas', true),
  ('Administrador', 'canEditVendas', true),
  ('Administrador', 'canDeleteVendas', true),
  ('Administrador', 'canManageUsers', true),
  ('Administrador', 'canCreateUsers', true),
  ('Administrador', 'canEditUsers', true),
  ('Administrador', 'canDeleteUsers', true),
  ('Administrador', 'canAccessAdminConfig', true),
  ('Administrador', 'canAccessAdministracao', true),
  ('Administrador', 'canAccessControleAcessos', true),
  ('Administrador', 'canManageEmpresas', true),
  ('Administrador', 'canEditEmpresas', true),
  ('Administrador', 'canViewEmpresas', true),
  ('Administrador', 'canAccessFinancialReports', true),
  ('Administrador', 'canViewDashboard', true),
  ('Administrador', 'canExportRelatorios', true),
  ('Administrador', 'canAccessResultados', true),
  ('Administrador', 'canViewMetricas', true),
  ('Administrador', 'canSyncResultados', true),
  ('Administrador', 'canAccessAcademy', true),
  ('Administrador', 'canManageAcademy', true),
  ('Administrador', 'canCreateTreinamentos', true),
  ('Administrador', 'canEditTreinamentos', true),
  ('Administrador', 'canDeleteTreinamentos', true),
  ('Administrador', 'canAssignTreinamentos', true),
  ('Administrador', 'canViewProgressoEquipe', true),
  ('Administrador', 'canAccessConfiguracoes', true),
  ('Administrador', 'canEditConfiguracoes', true),
  ('Administrador', 'canManageDepartamentos', true),
  ('Administrador', 'canManageMotivos', true),
  ('Administrador', 'canManageOrigens', true),
  ('Administrador', 'canManageTemperaturas', true),
  ('Administrador', 'canManageWhatsApp', true),
  ('Administrador', 'canManageMensagens', true),
  ('Administrador', 'canManageDocumentos', true),
  ('Administrador', 'canManageProdutos', true),
  ('Administrador', 'canAccessPersonas', true),
  ('Administrador', 'canCreatePersonas', true),
  ('Administrador', 'canEditPersonas', true),
  ('Administrador', 'canDeletePersonas', true),
  ('Administrador', 'canAccessGatilhos', true),
  ('Administrador', 'canCreateGatilhos', true),
  ('Administrador', 'canEditGatilhos', true),
  ('Administrador', 'canDeleteGatilhos', true),
  ('Administrador', 'canAccessAPIs', true),
  ('Administrador', 'canManageAPIs', true),
  ('Administrador', 'canTestAPIs', true),
  ('Administrador', 'canManageWebhooks', true),
  ('Administrador', 'canAccessNotificacoes', true),
  ('Administrador', 'canAccessMinhaConta', true),
  ('Administrador', 'canAccessAjuda', true),
  ('Administrador', 'canAccessRelatorios', true),
  ('Proprietário', 'canViewAuthenticator', false),
  ('Proprietário', 'canManageAuthenticator', false),
  ('Proprietário', 'canAssignAuthenticator', false),
  ('Proprietário', 'canViewAuditLogs', false),
  ('Proprietário', 'canViewControleAgentes', false),
  ('Proprietário', 'canCreateControleAgentes', false),
  ('Proprietário', 'canEditControleAgentes', false),
  ('Proprietário', 'canDeleteControleAgentes', false),
  ('Proprietário', 'canToggleControleAgentes', false),
  ('Proprietário', 'canAccessAgentesIA', false),
  ('Proprietário', 'canEditAgentesIA', false),
  ('Proprietário', 'canDeleteAgentesIA', false),
  ('Proprietário', 'canCreateAgentesIA', false),
  ('Proprietário', 'canManageInstancias', false),
  ('Proprietário', 'canViewVariaveis', false),
  ('Proprietário', 'canEditVariaveis', false),
  ('Proprietário', 'canManageCadencias', false),
  ('Proprietário', 'canManageFollowups', false),
  ('Proprietário', 'canManageIntegracoes', false),
  ('Proprietário', 'canViewTemplates', true),
  ('Proprietário', 'canCreateTemplates', false),
  ('Proprietário', 'canEditTemplates', false),
  ('Proprietário', 'canDeleteTemplates', false),
  ('Proprietário', 'canViewEventos', true),
  ('Proprietário', 'canCreateEventos', false),
  ('Proprietário', 'canEditEventos', false),
  ('Proprietário', 'canDeleteEventos', false),
  ('Proprietário', 'canManageEvents', true),
  ('Proprietário', 'canManageEventos', false),
  ('Proprietário', 'canCreateIALigacao', false),
  ('Proprietário', 'canDispararIALigacao', false),
  ('Proprietário', 'canToggleIALigacao', false),
  ('Proprietário', 'canViewIALigacaoLogs', false),
  ('Proprietário', 'canDispararEventos', false),
  ('Proprietário', 'canRedispararEventos', false),
  ('Proprietário', 'canAprovarCampanhas', false),
  ('Proprietário', 'canProgramarCampanhas', false),
  ('Proprietário', 'canViewClientes', true),
  ('Proprietário', 'canAddClientes', false),
  ('Proprietário', 'canEditClientes', false),
  ('Proprietário', 'canDeleteClientes', false),
  ('Proprietário', 'canImportClientes', false),
  ('Proprietário', 'canUploadBase', false),
  ('Proprietário', 'canEditContatos', true),
  ('Proprietário', 'canDeleteContatos', false),
  ('Proprietário', 'canValidarImportacao', false),
  ('Proprietário', 'canGovernancaDados', false),
  ('Proprietário', 'canAccessOptOutGlobal', false),
  ('Proprietário', 'canAccessRecepcao', false),
  ('Proprietário', 'canReadQRCode', false),
  ('Proprietário', 'canGenerateInvites', true),
  ('Proprietário', 'canAccessKanban', true),
  ('Proprietário', 'canEditAtendimentos', true),
  ('Proprietário', 'canDeleteAtendimentos', false),
  ('Proprietário', 'canViewProspeccao', true),
  ('Proprietário', 'canCreateProspeccao', false),
  ('Proprietário', 'canEditProspeccao', false),
  ('Proprietário', 'canDeleteProspeccao', false),
  ('Proprietário', 'canManageProspeccaoEquipes', false),
  ('Proprietário', 'canViewVendas', true),
  ('Proprietário', 'canCreateVendas', true),
  ('Proprietário', 'canEditVendas', false),
  ('Proprietário', 'canDeleteVendas', false),
  ('Proprietário', 'canManageUsers', false),
  ('Proprietário', 'canCreateUsers', false),
  ('Proprietário', 'canEditUsers', false),
  ('Proprietário', 'canDeleteUsers', false),
  ('Proprietário', 'canAccessAdminConfig', false),
  ('Proprietário', 'canAccessAdministracao', false),
  ('Proprietário', 'canAccessControleAcessos', false),
  ('Proprietário', 'canManageEmpresas', false),
  ('Proprietário', 'canEditEmpresas', false),
  ('Proprietário', 'canViewEmpresas', true),
  ('Proprietário', 'canAccessFinancialReports', true),
  ('Proprietário', 'canViewDashboard', true),
  ('Proprietário', 'canExportRelatorios', true),
  ('Proprietário', 'canAccessResultados', true),
  ('Proprietário', 'canViewMetricas', true),
  ('Proprietário', 'canSyncResultados', false),
  ('Proprietário', 'canAccessAcademy', false),
  ('Proprietário', 'canManageAcademy', false),
  ('Proprietário', 'canCreateTreinamentos', false),
  ('Proprietário', 'canEditTreinamentos', false),
  ('Proprietário', 'canDeleteTreinamentos', false),
  ('Proprietário', 'canAssignTreinamentos', false),
  ('Proprietário', 'canViewProgressoEquipe', false),
  ('Proprietário', 'canAccessConfiguracoes', false),
  ('Proprietário', 'canEditConfiguracoes', false),
  ('Proprietário', 'canManageDepartamentos', false),
  ('Proprietário', 'canManageMotivos', false),
  ('Proprietário', 'canManageOrigens', false),
  ('Proprietário', 'canManageTemperaturas', false),
  ('Proprietário', 'canManageWhatsApp', false),
  ('Proprietário', 'canManageMensagens', false),
  ('Proprietário', 'canManageDocumentos', false),
  ('Proprietário', 'canManageProdutos', false),
  ('Proprietário', 'canAccessPersonas', false),
  ('Proprietário', 'canCreatePersonas', false),
  ('Proprietário', 'canEditPersonas', false),
  ('Proprietário', 'canDeletePersonas', false),
  ('Proprietário', 'canAccessGatilhos', false),
  ('Proprietário', 'canCreateGatilhos', false),
  ('Proprietário', 'canEditGatilhos', false),
  ('Proprietário', 'canDeleteGatilhos', false),
  ('Proprietário', 'canAccessAPIs', false),
  ('Proprietário', 'canManageAPIs', false),
  ('Proprietário', 'canTestAPIs', false),
  ('Proprietário', 'canManageWebhooks', false),
  ('Proprietário', 'canAccessNotificacoes', true),
  ('Proprietário', 'canAccessMinhaConta', true),
  ('Proprietário', 'canAccessAjuda', true),
  ('Proprietário', 'canAccessRelatorios', true),
  ('Master', 'canViewAuthenticator', true),
  ('Master', 'canManageAuthenticator', true),
  ('Master', 'canAssignAuthenticator', true),
  ('Master', 'canViewAuditLogs', true),
  ('Master', 'canViewControleAgentes', true),
  ('Master', 'canCreateControleAgentes', true),
  ('Master', 'canEditControleAgentes', true),
  ('Master', 'canDeleteControleAgentes', true),
  ('Master', 'canToggleControleAgentes', true),
  ('Master', 'canAccessAgentesIA', true),
  ('Master', 'canEditAgentesIA', true),
  ('Master', 'canDeleteAgentesIA', true),
  ('Master', 'canCreateAgentesIA', true),
  ('Master', 'canManageInstancias', true),
  ('Master', 'canViewVariaveis', true),
  ('Master', 'canEditVariaveis', true),
  ('Master', 'canManageCadencias', true),
  ('Master', 'canManageFollowups', true),
  ('Master', 'canManageIntegracoes', true),
  ('Master', 'canViewTemplates', true),
  ('Master', 'canCreateTemplates', true),
  ('Master', 'canEditTemplates', true),
  ('Master', 'canDeleteTemplates', true),
  ('Master', 'canViewEventos', true),
  ('Master', 'canCreateEventos', true),
  ('Master', 'canEditEventos', true),
  ('Master', 'canDeleteEventos', true),
  ('Master', 'canManageEvents', true),
  ('Master', 'canManageEventos', true),
  ('Master', 'canCreateIALigacao', true),
  ('Master', 'canDispararIALigacao', true),
  ('Master', 'canToggleIALigacao', true),
  ('Master', 'canViewIALigacaoLogs', true),
  ('Master', 'canDispararEventos', true),
  ('Master', 'canRedispararEventos', true),
  ('Master', 'canAprovarCampanhas', true),
  ('Master', 'canProgramarCampanhas', true),
  ('Master', 'canViewClientes', true),
  ('Master', 'canAddClientes', true),
  ('Master', 'canEditClientes', true),
  ('Master', 'canDeleteClientes', true),
  ('Master', 'canImportClientes', true),
  ('Master', 'canUploadBase', true),
  ('Master', 'canEditContatos', true),
  ('Master', 'canDeleteContatos', true),
  ('Master', 'canValidarImportacao', true),
  ('Master', 'canGovernancaDados', true),
  ('Master', 'canAccessOptOutGlobal', true),
  ('Master', 'canAccessRecepcao', true),
  ('Master', 'canReadQRCode', true),
  ('Master', 'canGenerateInvites', true),
  ('Master', 'canAccessKanban', true),
  ('Master', 'canEditAtendimentos', true),
  ('Master', 'canDeleteAtendimentos', true),
  ('Master', 'canViewProspeccao', true),
  ('Master', 'canCreateProspeccao', true),
  ('Master', 'canEditProspeccao', true),
  ('Master', 'canDeleteProspeccao', true),
  ('Master', 'canManageProspeccaoEquipes', true),
  ('Master', 'canViewVendas', true),
  ('Master', 'canCreateVendas', true),
  ('Master', 'canEditVendas', true),
  ('Master', 'canDeleteVendas', true),
  ('Master', 'canManageUsers', true),
  ('Master', 'canCreateUsers', true),
  ('Master', 'canEditUsers', true),
  ('Master', 'canDeleteUsers', true),
  ('Master', 'canAccessAdminConfig', true),
  ('Master', 'canAccessAdministracao', true),
  ('Master', 'canAccessControleAcessos', true),
  ('Master', 'canManageEmpresas', true),
  ('Master', 'canEditEmpresas', true),
  ('Master', 'canViewEmpresas', true),
  ('Master', 'canAccessFinancialReports', true),
  ('Master', 'canViewDashboard', true),
  ('Master', 'canExportRelatorios', true),
  ('Master', 'canAccessResultados', true),
  ('Master', 'canViewMetricas', true),
  ('Master', 'canSyncResultados', true),
  ('Master', 'canAccessAcademy', true),
  ('Master', 'canManageAcademy', true),
  ('Master', 'canCreateTreinamentos', true),
  ('Master', 'canEditTreinamentos', true),
  ('Master', 'canDeleteTreinamentos', true),
  ('Master', 'canAssignTreinamentos', true),
  ('Master', 'canViewProgressoEquipe', true),
  ('Master', 'canAccessConfiguracoes', true),
  ('Master', 'canEditConfiguracoes', true),
  ('Master', 'canManageDepartamentos', true),
  ('Master', 'canManageMotivos', true),
  ('Master', 'canManageOrigens', true),
  ('Master', 'canManageTemperaturas', true),
  ('Master', 'canManageWhatsApp', true),
  ('Master', 'canManageMensagens', true),
  ('Master', 'canManageDocumentos', true),
  ('Master', 'canManageProdutos', true),
  ('Master', 'canAccessPersonas', true),
  ('Master', 'canCreatePersonas', true),
  ('Master', 'canEditPersonas', true),
  ('Master', 'canDeletePersonas', true),
  ('Master', 'canAccessGatilhos', true),
  ('Master', 'canCreateGatilhos', true),
  ('Master', 'canEditGatilhos', true),
  ('Master', 'canDeleteGatilhos', true),
  ('Master', 'canAccessAPIs', true),
  ('Master', 'canManageAPIs', true),
  ('Master', 'canTestAPIs', true),
  ('Master', 'canManageWebhooks', true),
  ('Master', 'canAccessNotificacoes', true),
  ('Master', 'canAccessMinhaConta', true),
  ('Master', 'canAccessAjuda', true),
  ('Master', 'canAccessRelatorios', true)
ON CONFLICT (departamento, permissao) DO NOTHING;